#!/usr/bin/env zsh
#
# THIS FILE IS FOR USER SPECIFIC SETTINGS ONLY

skip_global_compinit=1
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
typeset -g POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true

export ZDOTDIR="${ZDOTDIR:-"$HOME/.zsh"}"
